// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCseNjGq-VT1YK_pnyEvCjm6UqDUQcx72g',
    appId: '1:673405683879:web:d2ada67543737dd8ecf382',
    messagingSenderId: '673405683879',
    projectId: 'campus4',
    authDomain: 'campus4.firebaseapp.com',
    storageBucket: 'campus4.appspot.com',
    measurementId: 'G-4KG96MBG1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI-AK38DAqGuwR7zLst0ivtSQAfVOOXRE',
    appId: '1:673405683879:android:aad7996b2bf96027ecf382',
    messagingSenderId: '673405683879',
    projectId: 'campus4',
    storageBucket: 'campus4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGnUdELerxS-kGxd3tiDBRLwIn49c0tGQ',
    appId: '1:673405683879:ios:1ac9d98035146ea0ecf382',
    messagingSenderId: '673405683879',
    projectId: 'campus4',
    storageBucket: 'campus4.appspot.com',
    androidClientId: '673405683879-p9jl5cdji0eaoh7n26i8j3ckhakq4lgo.apps.googleusercontent.com',
    iosBundleId: 'np.edu.digitech.schoolworksprolite',
  );
}
